### ISSUE TITLE
Attached lead becomes invisible when using Iris with Sildur's Enhanced Default

### ISSUE THREAD

**Issue by Psojed** [IrisShaders/Iris#1097]
### What happened?

Hello!

I'm using Iris with Sildur's Enhanced Default Fast shaders. I noticed that the lead (the leash part between the horse and the fence) becomes invisible for some reason. Attached are screenshots using abovementioned Sildur's shader and a comparison when using Complementary Shaders.

Using the same shader in Optifine displays the lead properly.

### Screenshots

![Sildurs](https://user-images.githubusercontent.com/12875358/146221057-c4118116-0534-4ea1-81bc-b9888a65200e.png)
![Complementary](https://user-images.githubusercontent.com/12875358/146221045-61ce72f5-de5b-4b5f-a147-0cc852a98b91.png)

### Minecraft Version

1.18

### Iris Version

iris-mc1.18.1-1.1.3.jar

### Sodium Version

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Operating System

Windows 7

### What is your GPU?

AMD RX 580

### Java Version

17.0.1.12.1

**Comment by M4TO0** [comment]
I`m using 1.26.2 and this bug seems to have returned for me at least

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/422c9917-09a6-4ba7-ab28-6bf60cfbfa11" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d44b6318-18f6-4162-8897-29383e50f632" />
The ropes dissapear whenever i have shaders enabled, i tested with solas and complementary (also i`m using the fabulously optimized pack)
