### ISSUE TITLE
Possible integration with my mod, proper implementation for mc_Entity attribute?

### ISSUE THREAD

**Issue by DarkShadow44** [IrisShaders/Iris#11]
Hello there, first off, thanks for that great project, this might be exactly what I'm looking for!

I'd like to base my own WIP project, LightOverhaul, on your shader implementation, since I need shaders as well. In a nutshell, I'm working on colored lighting (that, unlike Albedo and others doesn't bleed through walls). One part is the lighting engine reworks which is part of my mod, the other part is a shaderpack that takes advantage of that color information.
Currently I'm working on a hacked version of Optifine, but for various reasons I'm not too happy with that...

For my mod to work, I need to add two attributes for each block - skylightRGB and blocklightRGB. Since I don't know too much about the shader pipeline, it would be very useful for me to see how mc_Entity is implemented. Then I could (hopefully) work in the two custom attributes for my mod as well.

First Question, would be willing to implement mc_Entity so I could base my work on that? That would be very much appreciated!
And second question, would you be willing to accept a pull request for those two custom attributes once I got my mod and API finished?

**Comment by coderbot16** [comment]
Hi, and thanks! At this moment, the main focus of Iris is parity with OptiFine / ShadersMod shaders, so extensions to the shader pipeline such as adding skylightRGB and blocklightRGB probably won't be added to mainline Iris.

Proper support for `mc_Entity` will be implemented soon, since it's one of the only remaining things needed for Vaporwave-Shaderpack to work properly. The main challenge is just extending the vertex format in all of the right places. If you want to use those hooks, you're certainly allowed to fork Iris under the LGPLv3 license and use it for your mod as long as you follow the terms and give credit.

However, since it's unlikely that such a colored light system would be compatible with existing shaderpacks, I think that you probably don't need to worry about compatibility with existing shaderpacks, like Iris. It might be worth looking into [Canvas](https://github.com/grondag/canvas) instead, since Canvas enables shader-based rendering for Fabric without carrying the baggage of the OptiFine shader pipeline along with it. A lot of the code in Iris won't be relevant to you, and of the code that is relevant, you'll probably find similar facilities in Canvas.

Hope that helps!

**Comment by coderbot16** [comment]
`mc_Entity` and other vertex format extensions have been implemented in mainline Iris, hopefully that helps! I know I'm a bit late though...

Here's the relevant commits: https://github.com/IrisShaders/Iris/compare/f022b098806f...04436be53efe

Also, after thinking about it I think that it would be good to have some level of compatibility between colored light mods and shaders, it would be interesting to see how this would work. I'm tracking that specific request here: https://github.com/IrisShaders/Iris/issues/191
