### ISSUE TITLE
Can't change shaders in sodium compatible version

### ISSUE THREAD

**Issue by xFrah** [IrisShaders/Iris#113]
So I installed the sodium branch but I can't seem to find any gui or something to change between shaders. Am I missing something?

**Comment by xFrah** [comment]
Oh neverming, I got it working by using the config file, but is there a way to do it in the game?

**Comment by IMS212** [comment]
As of now there is no GUI on the official repo, however there are forks (namely https://github.com/FoundationGames/Iris/tree/gui_config_experimental) with a GUI. (Please test issues on trunk before reporting here however)

**Comment by xFrah** [comment]
Is trunk sodium compatible aswell?

**Comment by IMS212** [comment]
You can also report issues here with sodium compatibility, just make sure it’s the official repo having issues as well and not just the forks please.

**Comment by xFrah** [comment]
Hm I don't quite understand because I'm not a great github user, but I'll do as you say, thanks.

**Comment by DragonEggBedrockBreaking** [comment]
> Hm I don't quite understand because I'm not a great github user, but I'll do as you say, thanks.
Basically:

- A repo (short for repository) is code that someone has written.
- A branch is part of that repository which has different code, e.g. 'Trunk' and 'Sodium Compatibility' are branches.
- A fork is like a copy of the code, that a third party has modified.
- Someone has forked this repository, and added an experimental GUI (graphical user interface) to select shaders.
- If you experience an issue with the original iris, simply create an issue report here.
- If you experience an issue with the fork, you need to do the following:
- - - Check if the issue occurs on normal iris, or just on the fork.
- - - If it occurs on normal iris as well, then report it here.
- - - If it occurs on the fork, then report it on the discord server (making sure that you mention it is an issue with the fork), because the specific fork has 'issues' disabled, and also because the people here may not be as familiar with the fork's code.

Do you understand now?

**Comment by xFrah** [comment]
Oh ok I needed the last part, thank you very much.
