### ISSUE TITLE
Blackscreen with RudoPlays Shaders in 1.16.5 with sodium compatibility

### ISSUE THREAD

**Issue by Edx09** [IrisShaders/Iris#119]
![Bild_2021-02-22_082527](https://user-images.githubusercontent.com/69675847/108675743-84d8cc00-74e7-11eb-8a8e-4603e65d7df2.png)
Looks like that ⬆️ 

I think its the same issue as in #57

**Comment by coderbot16** [comment]
Chocapic13's shaders are known to be broken under Iris (of which RudoPlays is a derivative), the only shaderpacks supported currently are Sildur's Vibrant Shaders v1.283 and XorDev's shaderpacks.

Support for Chocapic13's shaders will come in the future, however since so few shaders work currently, it isn't practical to list every shader pack that *isn't* supported, thus I'll close this issue for now.
