### ISSUE TITLE
Build Server

### ISSUE THREAD

**Issue by josephworks** [IrisShaders/Iris#12]
I have noticed that there is not a build system in place. Since I will be using this mod personally, I added it to my jenkins server:
http://ci.josephworks.net/job/IrisShaders

**Comment by josephworks** [comment]
Also, if you want the project to build, go to: http://192.168.0.11:8080/job/IrisShaders/build?token=buildnow
you can email me a token that you would like to use at smartech56@gmail.com

Since I do not have repo admin, Jenkins can't automatically build for some reason. Ill look for another way.

**Comment by coderbot16** [comment]
I haven't set up a build system for prebuilt jars just yet because the mod isn't really ready for widespread use. Once it's ready for more widespread usage I will likely set up a build system using GitHub Actions + GitHub Releases.

Perhaps you can configure Jenkins to poll the repository every now and then instead of waiting for push events over a webhook?

**Comment by josephworks** [comment]
That's a good idea, I'll try that.

**Comment by Lolothepro** [comment]
Noted the passage to brachyura
