### ISSUE TITLE
Iris ignores passed-in vertex normals, messing up smooth shading

### ISSUE THREAD

**Issue by haubna** [IrisShaders/Iris#1406]
### What happened?

BufferBuilder doesn't allow smooth shading or triangles with Iris (shaders enabled).

### Minecraft Version

Minecraft 1.18.2

### Iris Version

iris-mc1.18.2-1.2.4-build.38.jar

### Sodium Version

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Operating System

Windows 10 64-bit

### What is your GPU?

RTX 2080 Ti

### Java Version

Java 17

### Additional context

The function iris$beforeNext currently just drops the normals supplied to it which makes it impossible to have smooth shaded surfaces. It also only supports quads right now which makes it impractible for triangle meshes (used by the physics mod).
https://github.com/IrisShaders/Iris/blob/trunk/src/main/java/net/coderbot/iris/mixin/vertices/MixinBufferBuilder.java

**Comment by PepperCode1** [comment]
I am not sure about the exact reason the passed normals are not used, but I suspect that it is due to block rendering using the light face normal instead of the actual normal. If this is the only use for this normal calculation, the issue can be fixed by either modifying quad baking and block rendering to use the correct pre-baked normal vectors or only calculating normals if the existing normals consist only of -1, 0, or 1.
Also, the drawMode should be checked for the number of vertices so the assumption about quads can be removed.

**Comment by coderbot16** [comment]
Note for clarification: While shader packs require a tangent, normal, and binormal to do parallax effects, since the binormal must be orthogonal to the other two vectors, it can be computed from them as long as there is a boolean "orientation" to figure out whether it needs to be flipped after taking the cross product of the tangent and normal vectors.

**Comment by Lolothepro** [comment]
It's not fixed?
