### ISSUE TITLE
Support for Vulkan Mod

### ISSUE THREAD

**Issue by Zorklis** [IrisShaders/Iris#1515]
Fabric now has a [Vulkan Renderer mod](https://github.com/xCollateral/VulkanMod) that rewrites Minecraft OpenGL renderer to use Vulkan API. 
It's a work in progress but it's very promising, currently Iris crashes on it

**Comment by IMS212** [comment]
We do not have any plans to support Vulkan replacement mods as of now, as it would require a major rewrite of the Iris pipeline.

**Comment by NaiNonTH** [comment]
Understandable

**Comment by DioEgizio** [comment]
> but even if devs rewrote the mod to use vulkan, there'd no compatible shaders as they are all using opengl

vulkan supports GLSL

**Comment by LiberteIV** [comment]
> We do not have any plans to support Vulkan replacement mods as of now, as it would require a major rewrite of the Iris pipeline.

That are sad news, it's understandable ofcourse that you might not want to take that effort, at the same time i tested myself OpenGL standard API vs VulkanAPI fabricmod and the result was an average 400 FPS gain... using OpenGL instead of Vulkan is like throwing money out of the window, it's wasted performance. Sodium with Vulkan would be amazing, but they already said they won't do it... having my hopes up for optifine now.

**Comment by IMS212** [comment]
This is not true. Vulkan by itself gives no performance improvement, and is really hard to mess up. It’s *possible* to get slightly better performance by utilizing features of Vulkan, but Vulkan itself will do nothing for Minecraft, better programming will.

**Comment by LiberteIV** [comment]
> This is not true. Vulkan by itself gives no performance improvement, and is really hard to mess up. It’s _possible_ to get slightly better performance by utilizing features of Vulkan, but Vulkan itself will do nothing for Minecraft, better programming will.

Then i asume the VulkanAPI Mod must already be heavily optimized, or else i wouldn't get an average 400-600 FPS increase over OpenGL, 400-600 FPS isn't what i would call "slightly better", rather much better.

**Comment by Mauricio-MN** [comment]
Zink

**Comment by 1by1Xayd** [comment]
mah mah mah mah

**Comment by AArch64Gamer** [comment]
In 2026 now, I can confirm that VulkanMod brings a lot of optimization. With Sodium, Entity Culling, More Culling, Bobby, and Lithium, I get stable 54 FPS on my Mac with 32 chunk render distance. However when replacing Sodium with VulkanMod and adding VulkanBobby, I get 135 FPS, both instances running with 6GB allocated memory which should be more than enough, and both running at 2560x1440, and starting from idle temps (89°F) to prevent thermal throttling from adding bias to results. VulkanMod manages to get me 2.5 times the FPS with Sodium. With VSync enabled limiting both instances to 60 FPS, OpenGL had my computer running at 208°F while Vulkan was running at cool 113°F. Now I know that's not the best way to measure CPU overhead, but I think that says a lot about it though. There's also radiance shader that also replaces the rendering pipeline with Vulkan too, allowing for them to use hardware ray tracing, and it's much more performant than the ray tracing shaderpacks available for Iris.

**Comment by SussyNade** [comment]
What about now that mojang is gonna use vulkan?

**Comment by AArch64Gamer** [comment]
> What about now that mojang is gonna use vulkan?

What I think is gonna happen based on what I've seen on their Discord server is that Iris development will be halted in favor of their new shader loader called Aperture, which will be Vulkan-based, which is really cool since as seen with Radiance shader, Vulkan will allow hardware ray-tracing, and just faster performance with shaders in general, and more feature support for macOS which I'm personally excited about. Pretty much every mod will be supported besides those that rely on OpenGL like Voxy, Distant Horizons, Xaero's map, etc
