### ISSUE TITLE
Looking at player shadows are causing lag on all shaderpacks

### ISSUE THREAD

**Issue by BrtCgn** [IrisShaders/Iris#1564]
### What happened?

When i look at anyone's/my own player shadow it drops my FPS more than half, but whenever i stop looking at my player shadow FPS goes back to normal **_(It happens on every single shaderpack i try)._** 

### Screenshots

![2022-07-26_16 13 42](https://user-images.githubusercontent.com/110037885/181014924-5c0b526e-9ccc-4f5c-be8e-9635287d7373.png)
![2022-07-26_16 13 59](https://user-images.githubusercontent.com/110037885/181015005-0c89724e-e7e7-42cd-8b2f-b38263b7ff3e.png)

### Minecraft Version

1.19

### Iris Version

iris-mc1.19.1-1.2.6.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GTX 1650 Super

**Comment by coderbot16** [comment]
The performance difference is actually just caused by looking away from the sun. Iris's Advanced Shadow Frustum Culling is most effective when you're looking towards the sun, but it can only cull very little when you are looking in the exact opposite direction of the sun (ie, your own shadow) due to how it works. There's not really a bug here, just a limitation of the current shadow culling methods.

In the future there might be ways to overcome this, however.

**Comment by coderbot16** [comment]
Technical information on how the algorithm works can be found here:

https://github.com/IrisShaders/Iris/blob/1a5e5e6725550bcfe17cd16be49424911d944f50/src/main/java/net/coderbot/iris/shadows/frustum/advanced/AdvancedShadowCullingFrustum.java#L11-L30
