### ISSUE TITLE
Transparent nametags when looking at someone sneaking in front of water 

### ISSUE THREAD

**Issue by Justsnoopy30** [IrisShaders/Iris#161]
This also causes complete visibility with no fog when looking through the transparent nametag.

**Comment by coderbot16** [comment]
Could you attach a screenshot of what this looks like?

**Comment by Justsnoopy30** [comment]
![image](https://user-images.githubusercontent.com/33374736/110253288-1f58f680-7f4f-11eb-81c9-ed2ed75c7771.png)

**Comment by coderbot16** [comment]
Seems like yet another issue with translucency ordering. I guess player name tags are being rendered before water in that case, even when they should be getting rendered after water.

**Comment by thedocruby** [comment]
This is a problem in Vanilla, and countless bug reports have already been submitted (I just looked at this yesterday lol). This is fixed by enabling Fabulous graphics, but that is unfortunately not an option for Iris at the moment.

**Comment by coderbot16** [comment]
This appears to be because the name tags of shifting players use the `text` render layer instead of the `text_see_through` render layer. The `text_see_through` render layer does not write to the depth buffer and makes the text always pass the depth test (meaning that the text is always visible). However, the `text` render layer does write to the depth buffer, and it is seemingly writing to the depth buffer before water.

However, due to how Sildur's Vibrant Shaders works, if it wrote to the depth buffer after water, we would still see issues, just different ones.

I'm not sure if there is much that Iris can do here.

**Comment by thedocruby** [comment]
> I'm not sure if there is much that Iris can do here.

Another vanilla bug, perhaps?
Man, Mojang needs to get their game on!
(then again, maybe that's why they are somewhat reworking the rendering engine again in 1.17)
