### ISSUE TITLE
30 FPS on every setting except "potato" one (complementary shaders 1.19)

### ISSUE THREAD

**Issue by ShamPussyk** [IrisShaders/Iris#1639]
### What happened?

A bug happened!

### Screenshots

https://vimeo.com/manage/videos/751823440/privacy

### Log output

[latest.log](https://github.com/IrisShaders/Iris/files/9610480/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris-mc1.19.2-1.3.1.jar

### Operating System

Windows 10

### What is your GPU?

Nvidia GeForce GTX 1050Ti 4GB VRAM

### Additional context

potato 60 FPS
low — extreme 30 FPS

**Comment by unicornfartsparklez** [comment]
I'm having the same problem!!! Happened after latest update a I think the 27th of September.  Please help!

**Comment by NoEnd-yt** [comment]
I am using the "High" profile, and I am getting around 5 fps. My game is using my GPU and has enough RAM available. Java is up to date. I updated my mods yesterday and before that it was running perfectly fine with Complementary Shaders. I updated them and still 5 fps. I'll try to revert Iris to a previous version.

**Comment by FnigePython** [comment]
Do you have vsync on? Since the FPS looks very still

**Comment by NoEnd-yt** [comment]
Ok never mind, my issue was likely caused by low battery.

**Comment by coderbot16** [comment]
This is just vsync - VSync will drop you to 30 FPS if you can't consistently hit 60 FPS to keep your framerate stable. It only happens with higher profiles of Complementary Shaders because those higher profiles are putting much more load on your system and it is no longer able to consistently hit 60 FPS.

Disable VSync or reduce your graphics settings to fix the issue.
