### ISSUE TITLE
Map Rotation

### ISSUE THREAD

**Issue by Electrocutor** [IrisShaders/Iris#1697]
### What happened?

It seems that _s and _n maps do not rotate when the albedo texture does.

### Screenshots

https://i.imgur.com/eLlETcg.jpg

### Minecraft Version

1.18.2

### Iris Version

iris-mc1.18.2-1.4.0.jar

### Operating System

WIndows 10

### What is your GPU?

Nvidia GTX 1080ti

**Comment by PepperCode1** [comment]
Iris only loads PBR textures; it does not apply them. That is up to the shaderpack to do, so this is either a shaderpack bug or it is a shaderpack limitation, in which case it is a resource pack bug.

**Comment by Electrocutor** [comment]
The shader is BSL, and the _n and _s textures are correctly oriented with Optifine. The resource pack is a custom one I made to test after seeing something wrong; it consists of only 3 files, stone.png, stone_n.png, and stone_s.png. In the screenshot, the one that looks right has a 0 degree rotation in the default blockstate; the other 3 have varied levels of rotation and mirror as per the mojang blockstate.

**Comment by PepperCode1** [comment]
Do you have the alternate blocks option enabled on Optifine?

**Comment by coderbot16** [comment]
Without any response or resource pack to test with, and with the fact that we don't know of a plausible way that Iris could cause this, there's not much we can do here. If we can have a resource pack that clearly reproduces/demonstrates the issue that we can download, then this can be reopened, otherwise trying to look for an issue would just be guesswork.
