### ISSUE TITLE
Iris shaders do not work anymore on 1.16.5 on Amd gpus

### ISSUE THREAD

**Issue by costantino2000** [IrisShaders/Iris#1768]
### What happened?

After updating my gpu driver from 22.6.1 to 22.11.2 the shaders stopped working on Minecraft 1.16.5, but they still work with Optifine and with Iris on other versions like 1.19.2. The log says:
```
Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Failed to compile FRAGMENT shader for program centerDepthSmooth.fsh
```

### Screenshots
1.16.5 (the shaders are selected in the settings):
![2022-12-04_22 31 43](https://user-images.githubusercontent.com/86307814/205516808-89bc74c4-55b1-4bc8-bb34-94a04438fb6f.png)
![2022-12-04_22 36 48](https://user-images.githubusercontent.com/86307814/205517238-fb945b3f-6716-40dd-a9a4-37b90b29756e.png)
1.19.2:
![2022-12-04_22 46 30](https://user-images.githubusercontent.com/86307814/205517312-da30fa47-c962-4b28-bf3c-7ff2b0cf3db1.png)

### Log output
[latest.log](https://github.com/IrisShaders/Iris/files/10149554/latest.log)

### Minecraft Version

Minecraft 1.16.5

### Iris Version

Iris 1.4.3

### Operating System

Windows 10

### What is your GPU?

AMD RX 590

**Comment by maximumpower55** [comment]
This is due to the center depth smooth fragment shader using `output` as the name for its color output, on AMD `output` is a "reserved word", now this is logged as a warning for some reason but its actually a fatal error that stops the center depth smooth fragment shader from compiling, this was fixed in this [commit](https://github.com/IrisShaders/Iris/commit/5a06dbc4af0cb1c0f3edbf24ad1c36ccf2009430)

**Comment by maximumpower55** [comment]
Yes since this is a kinda major issue, we are only doing maintenance releases for 1.16.5 now

**Comment by maximumpower55** [comment]
Actually keep it open, there is a special label for this
