### ISSUE TITLE
Not work with sodium 0.4.7

### ISSUE THREAD

**Issue by Liyze09** [IrisShaders/Iris#1811]
### What happened?

A bug happened!

### Minecraft Version

Minecraft 1.19.3

### Iris Version

iris-mc1.19.3-1.4.6

### Operating System

macOS

### What is your GPU?

Apple M1

**Comment by YukiJr** [comment]
The Iris 1.4.6 does not support Sodium 0.4.7 due to 0.4.7 be more recent than this Iris version. The Iris will be only compatible to a specific Sodium version, which will be the most recent in the moment of that release.
In other words, you will need to wait for a new Iris version that will be compatible with the new Sodium version.

**Comment by Liyze09** [comment]
Thanks a lot.

**Comment by Liyze09** [comment]
Thank you very much.
