### ISSUE TITLE
Water is disconnected in certain conditions with Fayer3's enhanced default

### ISSUE THREAD

**Issue by Lolothepro** [IrisShaders/Iris#1823]
### What happened?

Water is disconnected in certain conditions with Fayer3's enhanced default

### Screenshots

![2023-01-02_20 16 14](https://user-images.githubusercontent.com/68275908/210271110-753c47e8-9cbc-4c31-b4a0-bdaffbd208c7.png)

### Minecraft Version

1.19.3

### Iris Version

1.5.0

### Operating System

Ubuntu 22.04

### What is your GPU?

GTX 1070

**Comment by coderbot16** [comment]
Not our bug. This is an issue that fayer3 will need to fix.

**Comment by Lolothepro** [comment]
> Not our bug. This is an issue that fayer3 will need to fix.

It only happens with Iris

**Comment by Lolothepro** [comment]
shaders/inc/gbuffers/default.vsh

```float fy = fract(vworldpos.y + 0.001);```

**Comment by Lolothepro** [comment]
Iris:

![2023-01-05_13 08 46](https://user-images.githubusercontent.com/68275908/210778514-9af2ed5c-bdc7-402e-86b2-d1eb99c0b110.png)

Optifine:

![2023-01-05_13 17 26](https://user-images.githubusercontent.com/68275908/210778560-56198763-6a16-4b9c-923b-17ecb207ea00.png)

Iris ```(float fy = fract(vworldpos.y + 0.01);```:

![2023-01-05_13 23 12](https://user-images.githubusercontent.com/68275908/210779471-544bae83-a0a1-44ab-b9f4-82082be55d9f.png)

**Comment by coderbot16** [comment]
Yes, it only happens with Iris, because Sodium uses a compact vertex format. But it is still an issue in the shader pack because the shader pack should be less sensitive to the exact positioning of water vertices. We have a hard coded patch for Sildur's enhanced default because it is not frequently updated but fayer3's enhanced default is more actively maintained so it should be fixed there.
