### ISSUE TITLE
Have the Sodium dependency in the fabric.mod.json

### ISSUE THREAD

**Issue by TechPro424** [IrisShaders/Iris#1833]
**Is your feature request related to a problem? Please describe.**
If I do not have Sodium installed along with Iris, I have to wait for the game to open just for it to tell me I need Sodium, which can take a long time on slower systems.

**Describe the solution you'd like**
Have the Sodium dependency in the `fabric.mod.json`, that way, it immediately tells me that I need Sodium

**Comment by coderbot16** [comment]
Fabric Loader's error reporting is not of acceptable quality and therefore we must make this compromise in order to provide an acceptable user experience for people not skilled in reading Fabric's confusing error messages. While it is certainly a waste of time for the game to load to completion before this fatal error is reported, that is far less of a waste of time than users being turned away or attempting to seek user support for help with understanding Fabric's generally incomprehensible error reporting.

In the future, it might be possible to rely on the loader's error messages if they are improved. Currently, only Forge has decent error messages for missing dependency mods, though Quilt Loader appears to be working on improved error reporting and this might be an option in the future.

For now, there's nothing to be done here.

**Comment by IMS212** [comment]
Done.
