### ISSUE TITLE
Add internal shaders

### ISSUE THREAD

**Issue by mrjasonn** [IrisShaders/Iris#2231]
**Is your feature request related to a problem? Please describe.**
You must use Optifine to use internal shaders, which is very annoying. Internal shaders allows you to disable "Old Lighting" which some people like the look of it disabled.

**Describe the solution you'd like**
To add it to Iris and be able to set it in game

**Describe alternatives you've considered**
Optifine, but it is so slow compared to Sodium

**Additional context**
Nothing

**Comment by Lolothepro** [comment]
Internal shaders was never added to Iris, and is not supported by Iris.

**Comment by jbritain** [comment]
Internal shaders is a legacy feature left over from shadersmod, when you had to embed the shaders in the jarfile. All it does with a normal jar is run the vanilla shaders through the optifine pipeline, which had a few side effects like the lack of old lighting.

It makes no sense to implement this in Iris since there's no reason to embed the shaders in the jarfile anymore.

**Comment by IMS212** [comment]
The answer is no; there are mods like Simply No Shading to do this.
