### ISSUE TITLE
Chests render through moving blocks in Sildur's Vibrant Lite

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#225]
Uploading 2021-04-01 12-31-44.mp4…
Happens in the normal sodium compatible iris (most recent version) and in starline iris (most recent version)

**Comment by edwloef** [comment]
https://user-images.githubusercontent.com/75493688/113282490-46ed7580-92e7-11eb-9c2a-4720704b0e17.mp4

sorry, the video didn't upload for some reason xD

**Comment by coderbot16** [comment]
Do you have any mods like Enhanced Block Entities installed? If so, try testing without them.

**Comment by edwloef** [comment]
![image](https://user-images.githubusercontent.com/75493688/113307517-7f9c4780-9305-11eb-9d3c-0c7f6c6f0a48.png)
I don't have EBE installed but maybe something similar to it? I'm honestly not sure but this is my mods list here.

**Comment by coderbot16** [comment]
After thinking about this, it is likely that this is due to moving blocks rendering with the `gbuffers_terrain` (terrain) program, instead of the `gbuffers_block` (block entities) program. Sildur's Vibrant Shaders expects terrain rendering to all happen at the start and not be interleaved with other program types, which causes the issue.
