### ISSUE TITLE
Lag when looking in certain direction.

### ISSUE THREAD

**Issue by Iysrvv** [IrisShaders/Iris#2256]
### What happened?

Whenever I look at a certain area I lag way more than other directions.
I heard it was something about the sun or the moon, but If there is a way to turn off a setting for this, please let me know.

### Screenshots

![image](https://github.com/IrisShaders/Iris/assets/122075678/120b5293-b7e7-4723-9ebd-006dde853776)
![image](https://github.com/IrisShaders/Iris/assets/122075678/2444cf6d-54d0-4c76-8221-416e5d50b794)
![image](https://github.com/IrisShaders/Iris/assets/122075678/e88ff114-6ff8-417c-aea2-c73c130525b6)
![image](https://github.com/IrisShaders/Iris/assets/122075678/dac58292-a2f0-47cd-bfbd-81e726d174c3)

### Minecraft Version

1.20.4

### Iris Version

1.20.4-1.6.17

### Operating System

Windows 11

### What is your GPU?

Nvidia Geforce RTX 2060 SUPER

**Comment by TheNukeLore** [comment]
Multiple factors can affect this, big one is entities and shadows

**Comment by Iysrvv** [comment]
Yeah, but ive tried on a new world and it still does it.

**Comment by Iysrvv** [comment]
It happens when I look away from the moon or the sun.

**Comment by Iysrvv** [comment]
Also I just fixed it by turning off a setting in my shaders, called realtime shadows. The thing is I want my game to have shadows in real time but without the lag.

**Comment by TheNukeLore** [comment]
Then it’s likely shadows, only fix is disabling shadows.. was typing this as you sent that, there is no fix as it’s just how shadows work.

**Comment by Iysrvv** [comment]
I saw a comment saying there may be a way around this though.

**Comment by schneidva** [comment]
Can confirm this bug, i have the same Problem. Its definitly related to the shadows and turning Real time shadows in complementary shaders off (as an example) like @Iysrvv said negates the performance hit.  And its definitly the sun/moon position. In some shaders i lose up to 50% of my FPS when looking away from the sun/moon. Also happens when being below bedrock level and looking down. Setup is 5800x/7900xtx.

**Comment by IMS212** [comment]
Sadly, this is not a bug; the code is working as intended.

**Comment by DadamaldaDad** [comment]
I've had this happen with multiple different shaders, including MakeUp Ultrafast, Super Duper Vanilla and Sildur's Vibrant Shaders. When V-Sync is enabled, the FPS seems locked at 30 instead of 60, when V-Sync is disabled, the FPS goes down as well.

The fact it's locked at 30 without fluctuating suggests that exactly half the frames are being dropped for some reason. It's likely not just a shaderpack issue. I'm on Linux Kubuntu with a GTX 1650, running nvidia-driver-580-open and Minecraft 1.20.1
