### ISSUE TITLE
Fix Compatibility with IrisExplorer

### ISSUE THREAD

**Issue by UltraBlackLinux** [IrisShaders/Iris#231]
Hey there,
I just discovered this amazing mod, that improves iris greatly: https://modrinth.com/mod/iris-explorer 
It has some incompatibility with recent changes though:
```
java.lang.IllegalAccessError: class de.metroite.irisexplorer.IrisExplorerMod tried to access private field net.coderbot.iris.Iris.reloadKeybind (de.metroite.irisexplorer.IrisExplorerMod and net.coderbot.iris.Iris are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @723ca036)
```
Please fix this or maybe merge the mods together ;)
Thanks!

Edit: Since I am too dumb to make pull requests: https://github.com/IrisShaders/Iris/blob/trunk/src/main/java/net/coderbot/iris/Iris.java#L50

**Comment by coderbot16** [comment]
Iris Explorer directly references internal Iris code, which I cannot support. Otherwise, I wouldn't be able to change internal code in the off chance that it broke some mod depending on it. A GUI is planned for Iris, but I don't think that using the resource pack screen is the best approach. Iris Explorer must be updated by its author, and at some point Iris will get a GUI of its own.

**Comment by Metroite** [comment]
I have since resolved the issue on my part! Sorry for the inconvenience.

**Comment by coderbot16** [comment]
Good to know, thanks! :+1:
