### ISSUE TITLE
Strange mixin-related crash on startup with 1.20.6 update of Do a Barrel Roll.

### ISSUE THREAD

**Issue by enjarai** [IrisShaders/Iris#2319]
### Minecraft Version

1.20.6

### Iris Version

iris-1.7.0+mc1.20.6.jar

### Sodium Version

sodium-fabric-0.5.8+mc1.20.6.jar

### Operating System

Windows 10 & Windows 11 tested

### What is your GPU?

NVIDIA GeForce RTX 4070 & AMD Radeon RX 6900 XT tested

### Java Version

Java 21

### Reproduction Steps

1. Install the latest versions of Iris, Sodium and Do a Barrel Roll in a new 1.20.6 instance.
2. Start the game.

### Crash Report file and latest.log

```shell
https://mclo.gs/Sa7D2me
https://paste.atlauncher.com/view/84a50c6c-a3d6-46b0-8c38-409e3a9df0a3
https://mclo.gs/zZpGIUv
Since some crash reports seem to be different from others, 
I will add additional crash reports here as they are reported 
to me for increased sample size:
https://mclo.gs/n7dBSvI
https://mclo.gs/LamDQPz (contains multiple logs for some reason)
https://mclo.gs/xX1ke6z
```

### Additional context

Hi, I develop Do a Barrel Roll, and have been encountering this issue running my latest update with Iris. I'm completely at a loss on how to diagnose this, which is why I'm bringing it up here. 

If there's anything I need to change on my end, please let me know, though I don't think I'm doing anything particularly cursed that I wasn't before...

**Comment by Dev0Louis** [comment]
After looking through the changes iris made I found the Issue.

It is because this [DABR Redirect](https://github.com/enjarai/do-a-barrel-roll/blob/arch/1.20.6/common/src/main/java/nl/enjarai/doabarrelroll/mixin/client/roll/GameRendererMixin.java) collides with this [Iris Mixin](https://github.com/IrisShaders/Iris/blob/1.20.6/src/main/java/net/irisshaders/iris/mixin/MixinModelViewBobbing.java#L79)

These are needed on both sides, because of the changes mojang made. But as they are both redirecting they don't work. 
I don't have solution ready, but hope that this clears up the confusion.

**Comment by enjarai** [comment]
I have found a suitable fix on my end. I'd still highly recommend Iris switch away from a `@Redirect` for this mixin though, as there are definitely better ways to handle it, and basically any mod that modifies the camera matrix will have to touch the specific line in question from 1.20.6 onwards.
