### ISSUE TITLE
Can't Use identity mod R control with Iris

### ISSUE THREAD

**Issue by user123456dev** [IrisShaders/Iris#2399]
Hello.. I am having an issue with Iris and Identity Mod which started a while ago. When I used the Architectury mod and identity on forge , it constantly crashes on preload, so i switched to fabric and it did work but can't use the Identity mod ability control which is R.. Everytime i press it it just says shader reload...

Excuse me.. if you can add a tab for customizing the shader reload button, along with others, this would be really grateful of you.. please..

**Comment by Luracasmus** [comment]
I think you can change Iris' keybinds in the Controls options menu, together with the rest of Minecraft's keybinds

**Comment by user123456dev** [comment]
Thank you, but excuse me can you tell me where is the controls menu?

**Comment by Luracasmus** [comment]
It's on the right side in the regular Minecraft Options menu

Iris' key binds are at Options -> Controls -> Key Binds, usually near the bottom

**Comment by Doziyuu** [comment]
Hello! I've tried changing the keybind, however it still reloads on R and the keybind I switched it to (up arrow) doesn't trigger the reload.

**Comment by Luracasmus** [comment]
I tried rebinding Reload Shaders to "Up Arrow" on my system (Windows 11, Iris 1.7.3+mc1.21) and it works

(Should look like this)
![image](https://github.com/user-attachments/assets/99c8b203-6a3e-46da-a04b-9ea82c36c928)

What OS and Iris version are you using, and are you sure that you don't already have something else bound to Up Arrow?

**Comment by Doziyuu** [comment]
I'm using 1.20.1 still, IRIS 1.7.2+ mc 1.20.1 . Windows 10.
![image](https://github.com/user-attachments/assets/19501629-dfb9-477a-a712-787faabced2e)
Looks like this for me. Still reloads shaders on r however!

**Comment by Doziyuu** [comment]
Since updating to a new 1.20.1 version of IRIS to see if that was the issue, I keep getting this error and shaders won't work at all:

deferred.fsh: deferred.fsh: 0(57) : error C7537: OpenGL does not allow 'sample' after a type specifier
0(57) : error C0000: syntax error, unexpected '=', expecting ';' or '(' at token "="
0(58) : error C0000: syntax error, unexpected ',', expecting "::" at token ","
0(59) : error C0000: syntax error, unexpected '-', expecting "::" at token "-"

**Comment by Luracasmus** [comment]
I think that might be an error caused by Iris' preprocessing, or an error in the shader pack itself that was previously fixed/hidden by Iris. Also probably the same problem as in https://github.com/IrisShaders/Iris/issues/2404

What shader pack are you using, and do all shader packs cause the same error message/problem?

Also, which version of Iris did you update to? `1.7.2` was already the latest for `mc1.20.1` as of writing
