### ISSUE TITLE
shaders not loading

### ISSUE THREAD

**Issue by F4T4LEclips3** [IrisShaders/Iris#2424]
### What happened?

when toggling shaders on nothing changes just the normal minecraft look refreshes 

### Log output

[latest.log](https://github.com/user-attachments/files/16372453/latest.log)

### Minecraft Version

1.19.2

### Iris Version

iris_mc1.19.2-1.6.1/1.6.11

### Operating System

windows 10

### What is your GPU?

nvidia rtx 4090

**Comment by Luracasmus** [comment]
Based on the log I think it might be a compatibility problem with "Chunks fade in", possibly because it's an outdated version or because it's simply incompatible with Iris

Try updating your mods to the latest versions available for your Minecraft version, and if that doesn't fix the issue, try removing "Chunks fade in"

**Comment by F4T4LEclips3** [comment]
thank you so much. That worked all i had to do was update that mod thanks again for the help

**Comment by Luracasmus** [comment]
I'm glad I could help! :) Feel free to close the issue as completed if you don't have any more questions
