### ISSUE TITLE
???

### ISSUE THREAD

**Issue by jiji-dot** [IrisShaders/Iris#2493]
### Minecraft Version

121.1

### Iris Version

iris-1.7.3+mc1.21.jar

### Sodium Version

sodium-fabric-0.5.11+mc1.21.jar

### Operating System

windows 11

### What is your GPU?

intel (r) uhd graphics 620

### Java Version

Java 21

### Reproduction Steps

????[crash-2024-10-16_15.16.01-client.txt](https://github.com/user-attachments/files/17395559/crash-2024-10-16_15.16.01-client.txt)

**Comment by Luracasmus** [comment]
Does the crash still occur without Physics Mod?

**Comment by Poopooracoocoo** [comment]
Physics Mod 3.0.20 is for Sodium 0.6.0-beta.2 and Iris 1.8.0-beta.4.

Since you're currently using Sodium 0.5.11 and Iris 1.7.3, you need to downgrade Physics Mod to 3.0.16: https://modrinth.com/mod/physicsmod/version/9hVF9EMT
For Physics Mod Pro, use v171: https://ko-fi.com/post/Physics-Mod-Pro-V171--Minecraft-1-21-1--Crash-Fi-D1D411KLHT
