### ISSUE TITLE
Bugs with Resolution Control+

### ISSUE THREAD

**Issue by coderbot16** [IrisShaders/Iris#288]
Apparently there are issues with Resolution Control+? These need to be investigated given that it is a useful mod to use with Iris.

**Comment by thedocruby** [comment]
I have no significant problems with RC+, other than the problems that are simply due to Iris having trouble with extremely high/low resolutions. Most of these issues are outlined in #236, and consistently occur at resolutions at 2k and above, as well as some other specific resolutions, regardless of whether or not RC+ is the method used to render high resolution. (The bugs also happen with a 4k monitor in fullscreen)

**Comment by matthewperiut** [comment]
With the latest sodium fork + iris branch with a change in resolution, the shadow map is disfigured in a really strange way

1x
![2021-06-06_05 17 51](https://user-images.githubusercontent.com/18296791/120919243-930dbb00-c686-11eb-87af-388e28ef66ce.png)
1.25x
![2021-06-06_05 18 13](https://user-images.githubusercontent.com/18296791/120919255-9bfe8c80-c686-11eb-888f-c376f8187d29.png)
0.75x
![2021-06-06_05 18 31](https://user-images.githubusercontent.com/18296791/120919265-a6b92180-c686-11eb-8718-f1aa6b70b738.png)

**Comment by sonophilos** [comment]
With iris-trunk and sodium-iris built 20210605, using Resolution Control+ to set the render resolution <1x also causes the skybox to shift. The appearance is that the field of view zooms in. It's hard to illustrate, but I've taken a few screens with my character looking at exactly the same point, and the position of the moon and stars directly reflects the distortion occurring.

Here's with shaders disabled, for a control case:
![fb2021-06-06_08 12 00-Vanilla](https://user-images.githubusercontent.com/85447234/120930788-a7ac7c00-c6a3-11eb-8561-67d27ef873c5.jpg)

Here's with Complementary enabled, with RC+ set to its usual 1.0x scale:
![fb2021-06-06_08 13 00-Comp1x](https://user-images.githubusercontent.com/85447234/120930811-b7c45b80-c6a3-11eb-9491-167d88587350.jpg)

Here's how much the moon shifts, just reducing RC+ to 0.75x scale:
![fb2021-06-06_08 13 19-Comp075x](https://user-images.githubusercontent.com/85447234/120930820-c90d6800-c6a3-11eb-8c65-b77d0ecd21a9.jpg)

Here's 0.5x, notice how large the stars appear? It really looks like I'm just looking at the center 'half' of the skybox texture at a time, and it 'pans' around twice as fast, thus the comparison to the FoV changing.
![fb2021-06-06_08 13 37-Comp05x](https://user-images.githubusercontent.com/85447234/120930850-eb9f8100-c6a3-11eb-857d-227a4801536b.jpg)

I really want to use Complementary, and would be willing to tolerate either slightly-jank reflections or disabling reflections in order to use it. RC+ is absolutely necessary for me to be able to do so at a playable framerate, but this issue it seemingly causes is a dealbreaker for me.

**Comment by coderbot16** [comment]
Seems like this hasn't been relevant for a while.
