### ISSUE TITLE
Godrays is displayed on a quarter of the screen

### ISSUE THREAD

**Issue by Ro-off** [IrisShaders/Iris#305]
![изображение](https://user-images.githubusercontent.com/53314439/120238155-ee921000-c264-11eb-84e4-191aa0d8fda4.png)

Version: iris-0.5.0 + sodium

Installed mods:
![изображение](https://user-images.githubusercontent.com/53314439/120238637-3f096d80-c265-11eb-9928-bee5cb77995a.png)

**Comment by thedocruby** [comment]
The Starlight mod is in Beta, and Iris is in alpha. Seeing as how shaders depend on the lighting engine, bugs should be expected. That being said, it would be helpful to know if this happens for you without Starlight as well, because I'm not sure how much godrays actually depend on the lighting engine. Also, keep in mind that this version of Iris was written for 1.16.5, and while i don't think there would be much of a difference from 1.16.4, it always helps to keep versions consistent.
