### ISSUE TITLE
Water reflections and other features are broken at extreme distances

### ISSUE THREAD

**Issue by CalXee** [IrisShaders/Iris#334]
![2021-06-09_10 10 45](https://user-images.githubusercontent.com/68349758/121371590-a7aeb500-c90b-11eb-9e69-8b5dc93321bd.png)
![2021-06-09_10 10 35](https://user-images.githubusercontent.com/68349758/121371593-a8474b80-c90b-11eb-9811-f9ecb7ccb45c.png)

**Comment by EminGT** [comment]
The reason is the cameraPosition uniform having floating point precission issues

**Comment by coderbot16** [comment]
OptiFine keeps the cameraPosition uniform within a certain value range and simply ensures that `cameraPosition - previousCameraPosition` remains the same, since otherwise they are arbitrary. Whenever it leaves the range, cameraPosition and previousCameraPosition are both shifted by a fixed amount to keep cameraPosition within range.
