### ISSUE TITLE
Unimplemented: "gbuffers_hand" program

### ISSUE THREAD

**Issue by EminGT** [IrisShaders/Iris#349]

**Comment by coderbot16** [comment]
This is because the first-person player hand is not rendered with shaders within the world, but rather as an overlay over the world after world rendering has completed like what vanilla does. This is a low priority for now since in-world shader based hand rendering is nontrivial to implement and has a lot of potential edge cases.

Perhaps https://github.com/tr7zw/FirstPersonModel is a good base for implementing in-world hand rendering.
