### ISSUE TITLE
weird shading with ctm and enhanced default

### ISSUE THREAD

**Issue by edwloef** [IrisShaders/Iris#412]
![2021-06-20_20 32 11](https://user-images.githubusercontent.com/75493688/122684648-e34c5780-d206-11eb-9f31-7ff3d178f907.png)
Using this: https://github.com/PepperCode1/ConnectedTexturesMod-Fabric/
and this: https://www.curseforge.com/minecraft/texture-packs/simple-ct

**Comment by KpauMupa** [comment]
And what's wrong here? Looks totally normal

**Comment by edwloef** [comment]
See the front of the temple (sorry bad screenshot)

You can see the connected sandstone being rendered dark, as if there were a shadow, but the smooth sandstone and terracotta are rendered correctly.

**Comment by edwloef** [comment]
This seems to be shaderpack independent, Satellence#3074 reported it on discord using a few different shaderpacks.

**Comment by AlsoNiko** [comment]
This is now confirmed as an issue with NCTM as well, and is likely an iris bug

**Comment by AlsoNiko** [comment]
Relevant messages https://discord.com/channels/756612889787498627/876567546390777856/879174668815319080

**Comment by coderbot16** [comment]
Upon investigation, this appears to be caused by directional shading not being properly disabled on blocks rendered with the Fabric Rendering API, except for those rendered with Indigo's vanilla model wrapper pathways.

It's possible that disabling directional shading in `World#getBrightness(Direction direction, boolean shade)` rather than in BakedQuad could work with / without Sodium and with / without FRAPI in all cases.
