### ISSUE TITLE
"Shader incompatability" tag

### ISSUE THREAD

**Issue by Diztend** [IrisShaders/Iris#417]
Not sure if this is the place to post it but there should be a tag for incompatable shaders

**Comment by NoComment1105** [comment]
spoken about in #307 (presently a draft)

**Comment by coderbot16** [comment]
At this point it makes the most sense for us to just focus on adding the needed features instead of trying to engineer warning screens that people will probably just click around anyways. There's only a few big-ticket shader pipeline features remaining, and all of the other issues will probably just end up being minor bugs & issues in Iris's implementation of shader pipeline features.
