### ISSUE TITLE
Iris shaders are super glitchy at far distances.

### ISSUE THREAD

**Issue by githubbingitup** [IrisShaders/Iris#423]
Minecraft 1.16.5 and the only mods are:
fabric-api-0.36.0+1.16
iris-mc1.16.5-1.0.2

But I've also tested it with the older version of Fabric API & Iris as well as with Sodium, Phosphor, Starlight, Lithium, and a ton of other performance mods. The problem never changes. It happens with every shader pack as well.

Basically, the further you go in-game the weirder it gets and the weird effects vary a bit depending on shaderpack. We're talking like 10m by 10m blocks out.
With Sildurs and Complementary, the animations of the leaves and grass slow down and moving through the world causes a glitchy stuter. With SEUS, the leaves and flowers rapidly flicker across the world.

Its very easy to replicate. Just teleport out like 10 million blocks and throw on any full-feature shaderpack.

**Comment by yitzy299** [comment]
Could you provide screenshots?

**Comment by githubbingitup** [comment]
Its not going to be visible in a screenshot, but I took a short video for you. 
I showcase it at 0 ~ 0, 50k ~ 50k, and then 10m ~ 10m with SEUS and Sildurs. 

Every other pack has similar issues as well. And as I said before, I'm only running Iris and Fabric, but this issue isn't fixed when using other performance mods. Also, if you noticed I turned F3 on at one point and my FPS was the same at 10m as it was at 0, so its not an FPS-related issue.

https://www.dropbox.com/s/7en9sy944l9g8nh/Base%20Profile%202021.06.22%20-%2012.15.53.17.mp4?dl=0
might take a second for it to fully upload

**Comment by coderbot16** [comment]
This likely has the same root cause as #334 - the cameraPosition uniform is having floating-point precision issues.

OptiFine appears to work around this through trying to keep the cameraPosition within a small range around the origin. This works because the importance of cameraPosition is not its exact value, but rather its relation to other values, in this case the previousCameraPosition uniform.

So, it's possible to modify cameraPosition however we want, as long as `cameraPosition - previousCameraPosition` remains the same after our modifications to its value.

**Comment by Farych** [comment]
> So, it's possible to modify cameraPosition however we want to maintain precision, as long as `cameraPosition - previousCameraPosition` remains the same after our modifications to its value.

Maybe you can add modified cameraPosition as extra setting? Cause this lags start at 600k away from spawn.
