### ISSUE TITLE
No skybox when render distance <4

### ISSUE THREAD

**Issue by maxigator** [IrisShaders/Iris#48]
The sky and clouds disappear and its black instead

**Comment by coderbot16** [comment]
This is interesting. It looks like Vanilla does not render the sky when the render distance is less than 4 because they will be entirely occluded by fog anyways.

However, OptiFine disables this, meaning that sky will render without regard for the render distance. Furthermore, it doesn't apply strong fog to the sky, sun and moon, meaning that they are visible even on low render distance. However, it does appear to disable the rendering of clouds on low render distance.

ShadersMod appears to do something similar, always rendering the sky no matter the render distance. However, it doesn't appear to disable cloud rendering on low render distances.

For now, I will try to match vanilla behavior (it looks like currently there's a bug in Iris causing the clear color to work properly, which should be a simple fix) but enabling the skybox on low render distance should probably be done as well.
