### ISSUE TITLE
Block entities are not rendered in the shadows pass when using iris+sodium 1.17, at least as of version 1.1

### ISSUE THREAD

**Issue by AlsoNiko** [IrisShaders/Iris#495]
Title, block entities are not producing any form of shadow, but only with sodium from the looks of things

**Comment by coderbot16** [comment]
Sodium has some special code to handle block entity rendering: https://github.com/IrisShaders/sodium-fabric/blob/c3086f48c536318a46f416b4b0f706e8faa7f90f/src/main/java/me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer.java#L270

The big difference is using `sodiumWorldRenderer.renderSectionManager.getVisibleBlockEntities()` to figure out what block entities are visible instead of using the vanilla chunk visibility lists when Sodium is installed. I'm not sure what the best way to do this is especially since the Sodium fork compiles against Iris instead of having Iris compile against the Sodium fork.
