### ISSUE TITLE
Add a donation link

### ISSUE THREAD

**Issue by maxigator** [IrisShaders/Iris#6]
You could create a discord server and a link to donate to support the project 
this would be great
I know this isn't really an issue but I didn't know where to post it

**Comment by maximeurban** [comment]
I would definitely donate!

**Comment by maximeurban** [comment]
@coderbot16

**Comment by coderbot16** [comment]
First off, thanks for the support!

I've made a Discord for the project and will make it public shortly.

Donations are a bit more complex because I'm not entirely sure how I'd like to do them. It's looking like there's a few people (such as @ColdIce1605) who'd like to contribute code the project, and I'm not sure if it's fair for me to collect the donations for my own personal purposes when I'm not the only one who's working on the code. I'd like to see what they think first. Also, I may wait until the project is a little bit farther along before I actually start collecting donations.

**Comment by ColdIce1605** [comment]
I'm more then fine with donations though I do want to think about it more before I agree completely.

**Comment by Pepe20129** [comment]
> I've made a Discord for the project and will make it public shortly.
Is there an update on the Discord?

**Comment by OverlordsIII** [comment]
https://discord.gg/jQJnav2jPu

**Comment by Pepe20129** [comment]
Thanks!

**Comment by coderbot16** [comment]
I've made a Patreon! It's available at https://www.patreon.com/coderbot or with the Sponsor button on GitHub.
