### ISSUE TITLE
Iris should add the option for change render quality

### ISSUE THREAD

**Issue by JuaniproXD** [IrisShaders/Iris#704]
The render quality is used for incrase or decrase the preformance and quality it can be good for low-end computers and 4k screens high levels are as antialiasing for example.

**Comment by AlsoNiko** [comment]
Is this for anti-alisting or for another feature?

**Comment by MeeniMc** [comment]
I think he means decreasing the render-resolution without changing the global screen resolution, so that 1) one can tradeoff image sharpness for the game rendering for higher FPS, while 2) maintaining super-crisp rendering of UI elements (which are still rendered at screen resolution. 

The anti-aliasing can be achieved by doing render-resolution larger than screen resolution, but that's not as much a compelling case, given that many shaders have their own TAA/FXAA integrated.

**Comment by JuaniproXD** [comment]
Yes, that is

**Comment by coderbot16** [comment]
Merging into https://github.com/IrisShaders/Iris/issues/757, which contains more information.
