### ISSUE TITLE
Add a way to dismiss the "Sodium isn't installed, you will have poor performance"

### ISSUE THREAD

**Issue by Southpaw1496** [IrisShaders/Iris#766]
## Is your feature request related to a problem? Please describe.
Because I have a Mac with an M1 chip, I've found that removing Sodium from Iris's JAR actually improves performance (see [this conversation in Discord](https://discord.com/channels/774352792659820594/849360601267830825/877471788534206496)). However, because I removed it, this means that whenever I run shaders I get a big warning that says "Sodium Isn't installed, you will have poor performance". I'd like to be able to dismiss this message since it obstructs important parts of my HUD and it doesn't apply in my (admittedly niche) case. 
## Describe the solution you'd like
I'd like to be able to toggle this message. I understand that it is useful for most people, but it isn't useful for me, it's just getting in the way. Ideally it would be a toggle in the shader packs selection screen, but if that is too accessible I wouldn't mind an obscure toggle hidden away, or even having to modify something in fabric-mod.json, I just don't want to have to modify raw code because I'll just break it.

## Describe alternatives you've considered
The only alternative I can think of is having a list of graphics cards that are worse with Sodium installed, and not display the warning if one of them is detected. I think my original suggestion of a toggle or even an obscure setting would be much better though.
## Additional context
In case anyone doesn't believe me about Sodium performance being worse, here are comparison images (also available in the Discord conversation linked above):

#### Without Sodium:
![Iris running without Sodum](https://cdn.discordapp.com/attachments/849360601267830825/877471785250074634/2021-08-18_09.31.24.png)

#### With Sodium:

![Iris running with Sodium](https://cdn.discordapp.com/attachments/849360601267830825/877471793538011186/2021-08-18_09.38.10.png)

**Comment by AlsoNiko** [comment]
The next release of sodium, 0.3.1 should fix these issues.

**Comment by Southpaw1496** [comment]
I still think that there should at least be an option, even if it's obscure and hidden, to disable the prompt in case you can't use sodium for whatever reason.

I agree that having the prompt there should be the default and is useful to most people, but if you can't have Sodium for whatever reason, there should be a way to get rid of it, even if it is obscure so that the average person can't do it and come complaining.

Why shouldn't there be?

**Comment by IMS212** [comment]
We don't want a simple button to turn it off, however a manual config change may be worth looking into.

**Comment by coderbot16** [comment]
As stated above, newer releases of Sodium include workarounds for Apple's M1 driver issues. They're basically the only drivers that are so genuinely problematic that Sodium runs worse on them than vanilla does.

Using Iris without Sodium removes most of the user-facing benefits of using Iris, and offering any sort of config option (even if hidden) to allow usage of Iris without Sodium will likely just end up being used as a cheap workaround for issues with better solutions (installing Indium, using the SWAP memory allocator, etc), ultimately resulting in a worse user experience overall.

While there are some legitimate reasons to run Iris without Sodium, these mostly have to do with debugging or development. As such, it is possible to run without Sodium in a development environment: https://github.com/IrisShaders/Iris/blob/ffaa91f25c1df750c8d7777e1448993401b82a6a/docs/development/sodium-compatibility.md#compiling-and-running-without-sodium

However, the warning message will stay, because it isn't really a problem when using Iris without Sodium for development or debugging. It's only an issue for people running Iris without Sodium for gameplay or normal usage, which we do not intend to support in any fashion, and wish to discourage as much as we can.
