### ISSUE TITLE
Lighting Doesn't Work Correctly At All

### ISSUE THREAD

**Issue by Yird1** [IrisShaders/Iris#83]
When using any shader pack, lighting will refuse to work correctly and will only show as vanilla lighting. I've tried all of sildurs shader packs yet none of them will work right.

I have yet to find out why, but I think it might be because of my NVIDIA card...? As looking at other issues I see people using AMD cards/apus with no problems.

Java 15
Using Minecraft 1.16.4
Fabric Loader 0.11.1
There are no other mods installed other than Iris

Also the multimc logs show a lot of errors: https://pastebin.com/RzQat5BN

Screenshots of lite and high:
![2021-01-18_22 20 03](https://user-images.githubusercontent.com/67247581/104995823-b7b90d00-59db-11eb-84eb-7098f2c56bf8.png)
![2021-01-18_22 34 29](https://user-images.githubusercontent.com/67247581/104996813-5f830a80-59dd-11eb-882d-dfe0dc06a354.png)

**Comment by IMS212** [comment]
Looks the same as mine (and every screenshot i've seen)

**Comment by coderbot16** [comment]
This is just the current state of Sildur's on Iris. Note that most of the fancy lighting effects happen around sunrise and sunset anyways with Sildur's.

The main issue here is the lack of shadow mapping support in Iris. Since many of the more fancy lighting effects in Sildur's shaders rely on shadow mapping, things will look a bit basic on Iris. This will change with time, however.

**Comment by Yird1** [comment]
Opps, looks like im just silly. I wonder if I should close the issues or not.

**Comment by Yird1** [comment]
I think I will.

**Comment by coderbot16** [comment]
This is still an issue, however I have filed it under #84 since that is more descriptive.
