### ISSUE TITLE
Even with Iris 1.1.2, no block outlines present when running Sildurs Enhanced Default.

### ISSUE THREAD

**Issue by respectablenoob-source** [IrisShaders/Iris#929]
### What happened?

No block outlines with Sildur's Enhanced default.

### Screenshots

![2021-10-12_11 05 00](https://user-images.githubusercontent.com/74622770/136860997-53eba6c5-f462-42b4-9c62-21b34c7780dc.png)

### Iris and Minecraft Version

iris 1.12, 1.17.1

### Are you running Sodium along with Iris?

Yes

### Operating System

Windows 10

### What is your GPU?

GTX 1660 Ti

### Java Version

Java 16

**Comment by IMS212** [comment]
Please send an f3 image and log file.

**Comment by respectablenoob-source** [comment]
> Please send an f3 image and log file.

Attached is F3 Debug screen
![2021-10-12_11 24 54](https://user-images.githubusercontent.com/74622770/136862528-6fe0cf79-57aa-4b68-ba15-b799ac816038.png)
n.

**Comment by IMS212** [comment]
We need the file from the logs folder named latest.log.

**Comment by EinfxchFinn** [comment]
Same issue.
Log: https://gist.github.com/EinfxchFinn/aac64275d28fdc0311920eb1c702ab8e
Iris version 1.1.2 and Enhanced Default v1.12

**Comment by coderbot16** [comment]
Thanks for the reports. This is caused by Iris not correctly writing the output of the vanilla line shader to the shader's framebuffers, because Enhanced Default does not provide its own gbuffers_basic shader program for lines. The code that's causing this issue is part of an attempt to reveal non-overridden core shaders, but it should be disabled / modified if a pack does not override gbuffers_basic.
